site_name: PlaceholderAPI 文档
theme:
  name: material
  language: zh
nav:
  - 首页: index.md
  - API 参考:
    - PlaceholderManager: api/placeholder-manager.md
    - PlaceholderRegistry: api/placeholder-registry.md
    - Utils: api/utils.md
